<a href="https://colab.research.google.com/github/m-ramaz/machine-learning-practice/blob/main/EDA/one_hot_encodings.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder

In [ ]:
df=pd.read_csv("/content/covid_toy.csv")

In [ ]:
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [ ]:
# to check null values in all columns of dataframe we use:
df.isnull().sum()
# fever me 10 values missing hai ab pehle isko imput krna pry ga mean se

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [ ]:
# koi bhi transformation apply krny se pehle hum hamesha us dataset ko train test split krei gay
from sklearn.model_selection import train_test_split

In [ ]:
df.drop(columns=['has_covid'])

    age  gender  fever   cough       city
0    60    Male  103.0    Mild    Kolkata
1    27    Male  100.0    Mild      Delhi
2    42    Male  101.0    Mild      Delhi
3    31  Female   98.0    Mild    Kolkata
4    65  Female  101.0    Mild     Mumbai
..  ...     ...    ...     ...        ...
95   12  Female  104.0    Mild  Bangalore
96   51  Female  101.0  Strong    Kolkata
97   20  Female  101.0    Mild  Bangalore
98    5  Female   98.0  Strong     Mumbai
99   10  Female   98.0  Strong    Kolkata

[100 rows x 5 columns]

In [ ]:
x_train,x_test,y_train,y_test=train_test=train_test_split(df.drop(columns=['has_covid']),df['has_covid'],test_size=0.2,random_state=0)

In [ ]:
df.shape

(100, 6)

In [ ]:
x_train.shape

(80, 5)

In [ ]:
x_test.shape

(20, 5)

In [ ]:
y_train.shape

(80,)

In [ ]:
y_test.shape

(20,)

# **one hot encoding**

In [ ]:
# to apply one hot encoding we will use class of OneHotEncoder
ohe=OneHotEncoder(drop='first',sparse_output=False)
x_train_gender_city=ohe.fit_transform(x_train[['gender','city']])
# testing data pr bhi lagay ga
x_test_gender_city=ohe.transform(x_test[['gender','city']])

In [ ]:
df['city'].value_counts()

city
Kolkata      32
Bangalore    30
Delhi        22
Mumbai       16
Name: count, dtype: int64

In [ ]:
df['gender'].value_counts()

gender
Female    59
Male      41
Name: count, dtype: int64

In [ ]:
x_train_gender_city.shape   # 4 column city ke 2 column gender ke total 6 column bn gye.

(80, 4)

# **OrdinalEncoding**

In [ ]:
# apply ordinal encoding on ordinal categorical data
oe=OrdinalEncoder()
x_train_cough=oe.fit_transform(x_train[['cough']]) # ye transformation array return krti hai.
x_test_cough=oe.transform(x_test[['cough']])

In [ ]:
x_train_cough.shape
# x_train  ye aik array return krta hai.

(80, 1)

# **SimpleImputer**

In [ ]:
si=SimpleImputer()
# fever ki missing values hai isle wahan ye apply hu ga.
x_train_fever=si.fit_transform(x_train[['fever']])
x_test_fever=si.transform(x_test[['fever']])

In [ ]:
x_train_fever.shape  # ab dekho yahan bhi values 80 rows show kr rha.

(80, 1)

In [ ]:
# ab ye tamam transformation mene alag alag apply ki hai lekin ab mujhy in sab ko ikhata krna pry ga takeh wo
# x_train aur x_test ki tarha pora ka pora aik sth dataframe nzr aye.

In [ ]:
# pehle me age ka column bhi nikal leta hu
x_train_age=x_train.drop(columns=['gender','fever','cough','city']).values  # ye bhi array return kr rha
x_test_age=x_test.drop(columns=['gender','fever','cough','city']).values

In [ ]:
x_train_cough.shape

(80, 1)

In [ ]:
x_train_transformed=np.concatenate((x_train_age,x_train_fever,x_train_gender_city,x_train_cough),axis=1)
x_test_transformed=np.concatenate((x_test_age,x_test_fever,x_test_gender_city,x_test_cough),axis=1)

In [ ]:
x_train_transformed.shape

(80, 7)

In [ ]:
# this is hectic work now we use columntransformer class bcz yahan sb kuch alag alag kr ke phr arrays ko concatenate kr ke phr unko dubar
# se df bna kr columns ke naam dena bht lengthy hai.

In [ ]:
# we use ColumnTransformer class